#pragma once

#define SPLIT_USB_DETECT
#define SPLIT_LED_STATE_ENABLE
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_WPM_ENABLE
#define SPLIT_TRANSPORT_MIRROR
#define SPLIT_OLED_ENABLE
#define SPLIT_HAPTIC_ENABLE
#define SPLIT_ACTIVITY_ENABLE

#define SERIAL_USART_TX_PIN GP7
#define SERIAL_USART_RX_PIN GP8

#define RGB_MATRIX_LED_COUNT 64
#define RGB_MATRIX_SPLIT {30, 34}

#define EE_HANDS
#ifdef INIT_EE_HANDS_RIGHT
#define WS2812_DI_PIN GP4
#else
#define WS2812_DI_PIN GP26
#endif

#define RGB_MATRIX_MAXIMUM_BRIGHTNESS 255
#define RGB_MATRIX_HUE_STEP 8
#define RGB_MATRIX_SAT_STEP 8
#define RGB_MATRIX_VAL_STEP 8
